version: 2
updates:
  # dependabot for GitHub Actions for this repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # day: "saturday"
      # time: '04:00'      
    open-pull-requests-limit: 10
    reviewers:
    - bennythejudge
    labels:
    - dependencies
  # dependabot for GitHub Actions for the template
  - package-ecosystem: "github-actions"
    directory: "template/.github/"
    schedule:
      interval: "weekly"
