name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  test:
    name: template setup test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Template Setup
        run: |
          git config user.name "Foo Bearer"
          ./setup.bash \
            "asdf-foo" \
            "foo --helo" \
            "asdf-community" \
            "ASDF Community" \
            "https://github.com/asdf-vm/asdf" \
            "https://asdf-vm.com" \
            "Apache-2.0"
            "yes"

      - name: Check setup result
        run: |
          set -xe
          ls -la .
          git log
          test ! -d template/
          grep "Apache" LICENSE
          test "master" = "$(git rev-parse --abbrev-ref HEAD)"
          ! git grep -F -e "<YOUR TOOL>" \
                   --or -e "<TOOL HOMEPAGE>" \
                   --or -e "<TOOL REPO>" \
                   --or -e "<TOOL CHECK>" \
                   --or -e "<YOUR NAME>" \
                   --or -e"<YOUR GITHUB USERNAME>"
